experiments: use BSLogUniform when min < 0, log=True
wcxve/elisa pull request #21
Opened 2024-04-12 13:07 UTC by xiesl97

2024-04-12 16:34 UTC, wcxve commented
From the log p.d.f plot, `BiSymmetricLogUniform` seems to be a uniform distribution instead of log-uniform. Although samples from BiSymmetricLogUniform.samples() are distributed as BiSymmetricLogUniform, the NUTS samples are not, see plots below. The key to make `BiSymmetricLogUniform` working for NUTS is to correctly implement the `log_prob` method, and `icdf` for nested sampling of `jaxns`.

```python
    import matplotlib.pyplot as plt
    import numpy as np
    from numpyro.distributions import LogUniform, Uniform
    from numpyro.infer import MCMC, NUTS

    u = Uniform(low=-100, high=100)
    logu = LogUniform(low=1e-3, high=1e3)
    bslogu = BiSymmetricLogUniform(low=-100, high=100)

    x1 = np.linspace(1e-3, 100, 10001)
    x2 = np.linspace(-100, 100, 10001)

    plt.figure()
    plt.plot(x1, logu.log_prob(x1), label='LogUniform')
    plt.plot(x2, u.log_prob(x2), label='Uniform')
    plt.plot(x2, bslogu.log_prob(x2), label='BiSymmetricLogUniform')
    plt.xlabel('x')
    plt.ylabel(r'$\ln$ prob')
    plt.legend()
    plt.show()

    plt.figure()
    sample = bslogu.sample(random.PRNGKey(0), (10000,))
    plt.hist(sample, 'auto', label='samples from BiSymmetricLogUniform.sample()')
    plt.show()

    def model():
        numpyro.sample('a', bslogu)
    sampler = MCMC(NUTS(model), num_warmup=500, num_samples=10000)
    sampler.run(random.PRNGKey(0))
    nuts_sample = sampler.get_samples(False)
    plt.figure()
    plt.hist(nuts_sample['a'], 'auto', label='samples from NUTS')
    plt.show()
```
<img width="595" alt="dist pdf" src="https://github.com/wcxve/elisa/assets/58248583/89f2b853-c0d3-4551-b8ae-edbc70a01f6d">

<img width="595" alt="samples" src="https://github.com/wcxve/elisa/assets/58248583/b39baca1-89a6-46cf-b358-bf5463ede44d">

<img width="595" alt="nuts samples" src="https://github.com/wcxve/elisa/assets/58248583/8c0f4c83-0b89-4093-a821-3db8b6850235">

2024-04-12 16:42 UTC, wcxve requested changes

2024-04-12 16:42 UTC, wcxve commented on src/elisa/models/bslog.py
> +    def log_prob(self, value):
log_prob must be correctly implemented, or this distribution is just a uniform distribution

2024-04-12 16:42 UTC, wcxve commented on src/elisa/models/bslog.py
> +    def cdf(self, value):
cdf must be correctly implemented, or this distribution is just a uniform distribution

2024-04-12 16:42 UTC, wcxve commented on src/elisa/models/bslog.py
> +    def icdf(self, value):
icdf must be correctly implemented, or this distribution is just a uniform distribution

2024-04-12 16:42 UTC, wcxve commented on src/elisa/models/bslog.py
> +    def mean(self):
Make sure the mean and variance are correct. Note that this can be tested against samples' mean and variance.

2024-04-12 16:42 UTC, wcxve commented on src/elisa/models/bslog.py
> +    def variance(self):
Make sure the mean and variance are correct. Note that this can be tested against samples' mean and variance.

2024-04-15 00:36 UTC, xiesl97 commented
```
u = Uniform(low=-100, high=100)
logu = LogUniform(low=0.01, high=np.log(100))
bslogu = BiSymLogUniform(low=bs.log(-100), high=bs.log(100))
```
![image](https://github.com/wcxve/elisa/assets/82627490/5b29e2dc-bb9f-4ac8-a86c-e087d602fd54)
![image](https://github.com/wcxve/elisa/assets/82627490/477afd87-a30f-47a0-920f-fedecfd5aede)
![image](https://github.com/wcxve/elisa/assets/82627490/0c9e9226-72ef-4f51-98f0-8ee7ae74627d)

2024-04-17 08:50 UTC, closed without merging